# Generated by Django 2.2.2 on 2021-04-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
